### WORKING ON IT ###

#docker:
#  needs: build
#  runs-on: ubuntu-latest
#  steps:
#    - name: Checkout
#      uses: actions/checkout@v5
#
#    - name: Download built jar
#      uses: actions/download-artifact@v4
#      with:
#        name: christmas-jar
#        path: ./artifact
#
#    - name: Set up Docker Build
#      uses: docker/setup-buildx-action@v2
#
#    - name: Build docker image (example)
#      run: |
#        docker build -t my-org/my-app:${{ github.sha }} \
#          --build-arg JAR_FILE=artifact/*.jar .